#!/usr/bin/env python3
"""Build MZ_SDP_strategy.pine (backtest version) from MZ_SDP.pine (the indicator).

The indicator stays the single source of the trading rules. This script copies it and
  1. replaces the indicator() declaration with strategy() (costs, capital),
  2. replaces the no-op block between the STRATEGY HOOKS markers with the order logic.

Edit MZ_SDP.pine, then run:  python3 tradingview/build_strategy.py
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE / "MZ_SDP.pine"
DST = HERE / "MZ_SDP_strategy.pine"

# Costs default to EURUSD: 0.00005 per unit per side = about 1 pip round trip (spread) on a
# 100k position. They live in the strategy Properties tab, where the user changes them per market.
# Margin 0: no leverage limit (Pine v6 defaults to 100% margin, which cannot carry 1%-risk FX positions);
# the size comes from the risk % only.
DECLARATION = (
    'strategy("MZ SDP Strategy — Standard Deviation Projection (Milad Zaker)", shorttitle = "MZ SDP Strategy", '
    'overlay = true, max_lines_count = 500, max_labels_count = 500, max_boxes_count = 300, max_bars_back = 2000, '
    'initial_capital = 10000, pyramiding = 1, commission_type = strategy.commission.cash_per_contract, '
    'commission_value = 0.00005, slippage = 2, margin_long = 0, margin_short = 0, process_orders_on_close = false)'
)

HEADER_NOTE = (
    "// BACKTEST (strategy) version, generated from MZ_SDP.pine by build_strategy.py - edit MZ_SDP.pine and rebuild.\n"
    "// Costs: strategy Properties tab (default about 1 pip round trip on EURUSD; crypto: commission in %).\n"
)

HOOKS = '''// ==== STRATEGY HOOKS BEGIN — orders of the backtest (generated by build_strategy.py)
const string G_BT = "📊 Backtest (strategy)"
float  iRiskPct  = input.float(1.0, "Risk per trade (% of equity)", minval = 0.01, step = 0.25, group = G_BT, tooltip = "Position size so that the stop costs this % of equity. Costs (spread / commission / slippage) are in the Properties tab: the default 0.00005 per unit per side is about 1 pip round trip on EURUSD; for crypto use a commission in %.")
string iWarnSize = input.string("Half size", "⚠ reduce-size signals", options = ["Full size", "Half size", "Skip"], group = G_BT, tooltip = "Signals the indicator marks '⚠ reduce size' (against the daily trend / bias or the 4h range).")
// one trade at a time, as a trader would: a signal is taken only when no position and no order of an earlier signal is open
var array<string> stratLive = array.new<string>()
f_stratOpen(Trade tr, string grade) =>
    bool ok = f_gradeRank(grade) >= f_gradeRank(iMinGrade) and strategy.position_size == 0 and stratLive.size() == 0 and not (tr.warn != "" and iWarnSize == "Skip")
    if ok
        float riskPx = math.abs(tr.entry - tr.stop)
        float qty = riskPx > 0 ? strategy.equity * iRiskPct / 100 / (riskPx * syminfo.pointvalue) : 0.0
        if tr.warn != "" and iWarnSize == "Half size"
            qty := qty / 2
        if syminfo.mincontract > 0
            qty := math.floor(qty / syminfo.mincontract) * syminfo.mincontract
        ok := qty > 0
        if ok
            stratLive.push(tr.id)
            strategy.entry(tr.id, tr.sell ? strategy.short : strategy.long, qty, limit = tr.market ? na : tr.entry, comment = (tr.sell ? "SELL " : "BUY ") + grade + (tr.warn != "" ? " ⚠" : ""))
            bool part = not na(tr.tp1) and iPartFrac < 1
            if part  // partial at -1 (or the 50%), stop not moved; the rest runs to the main target
                strategy.exit(tr.id + " p", tr.id, qty_percent = iPartFrac * 100, limit = tr.tp1, stop = tr.stop, comment_profit = "partial", comment_loss = "SL")
            strategy.exit(tr.id + " x", tr.id, limit = na(tr.tp1) or part ? tr.tpMain : tr.tp1, stop = tr.stop, comment_profit = "TP", comment_loss = "SL")
    ok
f_stratEvent(Trade tr, string ev) =>
    int k = stratLive.indexof(tr.id)
    if k >= 0
        bool unfilled = ev == "cancel" or ev == "expired" or ev == "void"
        if unfilled or ev == "close"  // news, or the indicator never entered: close whatever the emulator holds (no-op if nothing)
            strategy.close(tr.id, comment = ev == "close" ? "news" : ev == "void" ? "opened past SL" : ev)
        if unfilled  // and no order may stay behind
            strategy.cancel(tr.id)
            strategy.cancel(tr.id + " p")
            strategy.cancel(tr.id + " x")
        if unfilled or ev == "tp" or ev == "sl" or ev == "close"
            strategy.cancel(tr.id)  // an entry the emulator has not filled yet
            stratLive.remove(k)
    ev
// the indicator takes no fill after its last valid bar: cancel the entry at that bar's close so the emulator cannot fill it later
for t in trades
    if t.state == 0 and bar_index >= t.validUntil and stratLive.includes(t.id)
        strategy.cancel(t.id)
// a trade the indicator dropped without an event does not block the next signal
if stratLive.size() > 0
    for i = stratLive.size() - 1 to 0
        string sid = stratLive.get(i)
        bool alive = false
        for t in trades
            if t.id == sid
                alive := true
        if not alive
            strategy.cancel(sid)
            stratLive.remove(i)
// ==== STRATEGY HOOKS END'''


def main() -> int:
    src = SRC.read_text(encoding="utf-8")
    lines = src.split("\n")

    decl = [i for i, l in enumerate(lines) if l.startswith("indicator(")]
    if len(decl) != 1:
        sys.exit("expected exactly one indicator( line in %s" % SRC.name)
    lines[decl[0]] = DECLARATION
    out = "\n".join(lines)

    begin = out.find("// ==== STRATEGY HOOKS BEGIN")
    end = out.find("// ==== STRATEGY HOOKS END")
    if begin < 0 or end < 0 or out.count("// ==== STRATEGY HOOKS BEGIN") != 1 or out.count("// ==== STRATEGY HOOKS END") != 1:
        sys.exit("STRATEGY HOOKS markers missing or duplicated in %s" % SRC.name)
    end = out.index("\n", end)
    out = out[:begin] + HOOKS + out[end:]

    marker = "//@version=6\n"
    if marker not in out:
        sys.exit("//@version=6 line not found")
    out = out.replace(marker, HEADER_NOTE + marker, 1)

    out = re.sub(r"// ===== END OF SCRIPT: line \d+ —", "// ===== END OF SCRIPT: line %d —" % out.count("\n"), out)
    DST.write_text(out, encoding="utf-8")
    print("wrote %s (%d lines)" % (DST.relative_to(HERE.parent), out.count("\n")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
